version: '3.8'
  
services:
  app:
    container_name: swag
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DOTNET_RUNNING_IN_CONTAINER=true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ${SERVE_DIRECTORY}:/app/wwwroot