name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f docker/Dockerfile -t epidemicz/swag:latest .

  
  push_to_registry:
    needs: build    
    name: Push Docker Image to Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to registry
        run: docker image push epidemicz/swag:latest
